=== LegendaryMediaTV/EGP-Graphai/panta/bb-export-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "_id": {
        "type": "string",
        "pattern": "^[a-z0-9]+-[0-9]+$"
      },
      "version": {
        "type": "string",
        "minLength": 1
      },
      "chapter": {
        "type": "string",
        "pattern": "^[a-z0-9-]+-[0-9]+$"
      },
      "sequence": {
        "type": "string",
        "pattern": "^[0-9]+$"
      },
      "number": {
        "type": "number",
        "minimum": 1
      },
      "text": {
        "type": "string"
      },
      "paragraphs": {
        "type": "array",
        "items": {
          "type": "number",
          "minimum": 0
        }
      },
      "footnotes": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "text": {
              "type": "string"
            },
            "type": {
              "type": "string",
              "enum": ["trn", "var", "xrf", "map", "stu"]
            }
          },
          "required": ["text"],
          "additionalProperties": false
        }
      },
      "subtitle": {
        "type": "object",
        "properties": {
          "text": {
            "type": "string"
          },
          "footnotes": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "text": {
                  "type": "string"
                },
                "type": {
                  "type": "string",
                  "enum": ["trn", "var", "xrf", "map", "stu"]
                }
              },
              "required": ["text"],
              "additionalProperties": false
            }
          }
        },
        "required": ["text"],
        "additionalProperties": false
      }
    },
    "required": ["_id", "version", "chapter", "sequence", "number", "text"],
    "additionalProperties": false
  }
}

=== LegendaryMediaTV/EGP-Graphai/exports/bb/ASV1901/57-PHM.json
[
  {
    "_id": "asv-218001001",
    "version": "asv",
    "chapter": "philemon-1",
    "sequence": "218001001",
    "number": 1,
    "text": "Paul, a prisoner of Christ Jesus, and Timothy our brother, to Philemon our beloved and fellow-worker,",
    "paragraphs": [0]
  },
  {
    "_id": "asv-218001002",
    "version": "asv",
    "chapter": "philemon-1",
    "sequence": "218001002",
    "number": 2,
    "text": "and to Apphia our sister, and to Archippus our fellow-soldier, and to the church in thy house:"
  },
  {
    "_id": "asv-218001003",
    "version": "asv",
    "chapter": "philemon-1",
    "sequence": "218001003",
    "number": 3,
    "text": "Grace to you and peace from God our Father and the Lord Jesus Christ."
  },
  {
    "_id": "asv-218001004",
    "version": "asv",
    "chapter": "philemon-1",
    "sequence": "218001004",
    "number": 4,
    "text": "I thank my God always, making mention of thee in my prayers,"
  },
  {
    "_id": "asv-218001005",
    "version": "asv",
    "chapter": "philemon-1",
    "sequence": "218001005",
    "number": 5,
    "text": "hearing of thy love, and of the faith which thou hast toward the Lord Jesus, and toward all the saints;"
  },
  {
    "_id": "asv-218001006",
    "version": "asv",
    "chapter": "philemon-1",
    "sequence": "218001006",
    "number": 6,
    "text": "that the fellowship of thy faith may become effectual, in the knowledge of every good thing which is in you, unto Christ."
  },
  {
    "_id": "asv-218001007",
    "version": "asv",
    "chapter": "philemon-1",
    "sequence": "218001007",
    "number": 7,
    "text": "For I had much joy and comfort in thy love, because the hearts of the saints have been refreshed through thee, brother."
  },
  {
    "_id": "asv-218001008",
    "version": "asv",
    "chapter": "philemon-1",
    "sequence": "218001008",
    "number": 8,
    "text": "Wherefore, though I have all boldness in Christ to enjoin thee that which is befitting,"
  },
  {
    "_id": "asv-218001009",
    "version": "asv",
    "chapter": "philemon-1",
    "sequence": "218001009",
    "number": 9,
    "text": "yet for loveâ€™s sake I rather beseech, being such a one as Paul the aged, and now a prisoner also of Christ Jesus:"
  },
  {
    "_id": "asv-218001010",
    "version": "asv",
    "chapter": "philemon-1",
    "sequence": "218001010",
    "number": 10,
    "text": "I beseech thee for my child, whom I have begotten in my bonds, Onesimus,"
  },
  {
    "_id": "asv-218001011",
    "version": "asv",
    "chapter": "philemon-1",
    "sequence": "218001011",
    "number": 11,
    "text": "who once was unprofitable to thee, but now is profitable to thee and to me:"
  },
  {
    "_id": "asv-218001012",
    "version": "asv",
    "chapter": "philemon-1",
    "sequence": "218001012",
    "number": 12,
    "text": "whom I have sent back to thee in his own person, that is, my very heart:"
  },
  {
    "_id": "asv-218001013",
    "version": "asv",
    "chapter": "philemon-1",
    "sequence": "218001013",
    "number": 13,
    "text": "whom I would fain have kept with me, that in thy behalf he might minister unto me in the bonds of the gospel:"
  },
  {
    "_id": "asv-218001014",
    "version": "asv",
    "chapter": "philemon-1",
    "sequence": "218001014",
    "number": 14,
    "text": "but without thy mind I would do nothing; that thy goodness should not be as of necessity, but of free will."
  },
  {
    "_id": "asv-218001015",
    "version": "asv",
    "chapter": "philemon-1",
    "sequence": "218001015",
    "number": 15,
    "text": "For perhaps he was therefore parted from thee for a season, that thou shouldest have him for ever;"
  },
  {
    "_id": "asv-218001016",
    "version": "asv",
    "chapter": "philemon-1",
    "sequence": "218001016",
    "number": 16,
    "text": "no longer as a servant, but more than a servant, a brother beloved, specially to me, but how much rather to thee, both in the flesh and in the Lord."
  },
  {
    "_id": "asv-218001017",
    "version": "asv",
    "chapter": "philemon-1",
    "sequence": "218001017",
    "number": 17,
    "text": "If then thou countest me a partner, receive him as myself."
  },
  {
    "_id": "asv-218001018",
    "version": "asv",
    "chapter": "philemon-1",
    "sequence": "218001018",
    "number": 18,
    "text": "But if he hath wronged the at all, or oweth thee aught, put that to mine account;"
  },
  {
    "_id": "asv-218001019",
    "version": "asv",
    "chapter": "philemon-1",
    "sequence": "218001019",
    "number": 19,
    "text": "I Paul write it with mine own hand, I will repay it: that I say not unto thee that thou owest to me even thine own self besides."
  },
  {
    "_id": "asv-218001020",
    "version": "asv",
    "chapter": "philemon-1",
    "sequence": "218001020",
    "number": 20,
    "text": "Yea, brother, let me have joy of thee in the Lord: refresh my heart in Christ."
  },
  {
    "_id": "asv-218001021",
    "version": "asv",
    "chapter": "philemon-1",
    "sequence": "218001021",
    "number": 21,
    "text": "Having confidence in thine obedience I write unto thee, knowing that thou wilt do even beyond what I say."
  },
  {
    "_id": "asv-218001022",
    "version": "asv",
    "chapter": "philemon-1",
    "sequence": "218001022",
    "number": 22,
    "text": "But withal prepare me also a lodging: for I hope that through your prayers I shall be granted unto you."
  },
  {
    "_id": "asv-218001023",
    "version": "asv",
    "chapter": "philemon-1",
    "sequence": "218001023",
    "number": 23,
    "text": "Epaphras, my fellow-prisoner in Christ Jesus, saluteth thee;"
  },
  {
    "_id": "asv-218001024",
    "version": "asv",
    "chapter": "philemon-1",
    "sequence": "218001024",
    "number": 24,
    "text": "and so do Mark, Aristarchus, Demas, Luke, my fellow-workers."
  },
  {
    "_id": "asv-218001025",
    "version": "asv",
    "chapter": "philemon-1",
    "sequence": "218001025",
    "number": 25,
    "text": "The grace of our Lord Jesus Christ be with your spirit. Amen."
  }
]

=== LegendaryMediaTV/EGP-Graphai/exports/bb/YLT1898/57-PHM.json
[
  {
    "_id": "ylt-218001001",
    "version": "ylt",
    "chapter": "philemon-1",
    "sequence": "218001001",
    "number": 1,
    "text": "Paul, a prisoner of Christ Jesus, and Timotheus the brother, to Philemon our beloved and fellow-worker,",
    "paragraphs": [0]
  },
  {
    "_id": "ylt-218001002",
    "version": "ylt",
    "chapter": "philemon-1",
    "sequence": "218001002",
    "number": 2,
    "text": "and Apphia the beloved, and Archippus our fellow-soldier, and the assembly in thy house:"
  },
  {
    "_id": "ylt-218001003",
    "version": "ylt",
    "chapter": "philemon-1",
    "sequence": "218001003",
    "number": 3,
    "text": "Grace to you, and peace, from God our Father, and the Lord Jesus Christ!"
  },
  {
    "_id": "ylt-218001004",
    "version": "ylt",
    "chapter": "philemon-1",
    "sequence": "218001004",
    "number": 4,
    "text": "I give thanks to my God, always making mention of thee in my prayers,"
  },
  {
    "_id": "ylt-218001005",
    "version": "ylt",
    "chapter": "philemon-1",
    "sequence": "218001005",
    "number": 5,
    "text": "hearing of thy love and faith that thou hast unto the Lord Jesus and toward all the saints,"
  },
  {
    "_id": "ylt-218001006",
    "version": "ylt",
    "chapter": "philemon-1",
    "sequence": "218001006",
    "number": 6,
    "text": "that the fellowship of thy faith may become working in the full knowledge of every good thing that is in you toward Christ Jesus;"
  },
  {
    "_id": "ylt-218001007",
    "version": "ylt",
    "chapter": "philemon-1",
    "sequence": "218001007",
    "number": 7,
    "text": "for we have much joy and comfort in thy love, because the bowels of the saints have been refreshed through thee, brother."
  },
  {
    "_id": "ylt-218001008",
    "version": "ylt",
    "chapter": "philemon-1",
    "sequence": "218001008",
    "number": 8,
    "text": "Wherefore, having in Christ much boldness to command thee that which is fit-"
  },
  {
    "_id": "ylt-218001009",
    "version": "ylt",
    "chapter": "philemon-1",
    "sequence": "218001009",
    "number": 9,
    "text": "because of the love I rather entreat, being such an one as Paul the aged, and now also a prisoner of Jesus Christ;"
  },
  {
    "_id": "ylt-218001010",
    "version": "ylt",
    "chapter": "philemon-1",
    "sequence": "218001010",
    "number": 10,
    "text": "I entreat thee concerning my child-whom I did beget in my bonds-Onesimus,"
  },
  {
    "_id": "ylt-218001011",
    "version": "ylt",
    "chapter": "philemon-1",
    "sequence": "218001011",
    "number": 11,
    "text": "who once was to thee unprofitable, and now is profitable to me and to thee,"
  },
  {
    "_id": "ylt-218001012",
    "version": "ylt",
    "chapter": "philemon-1",
    "sequence": "218001012",
    "number": 12,
    "text": "whom I did send again, and thou him (that is, my own bowels) receive,"
  },
  {
    "_id": "ylt-218001013",
    "version": "ylt",
    "chapter": "philemon-1",
    "sequence": "218001013",
    "number": 13,
    "text": "whom I did wish to retain to myself, that in thy behalf he might minister to me in the bonds of the good news,"
  },
  {
    "_id": "ylt-218001014",
    "version": "ylt",
    "chapter": "philemon-1",
    "sequence": "218001014",
    "number": 14,
    "text": "and apart from thy mind I willed to do nothing, that as of necessity thy good deed may not be, but of willingness,"
  },
  {
    "_id": "ylt-218001015",
    "version": "ylt",
    "chapter": "philemon-1",
    "sequence": "218001015",
    "number": 15,
    "text": "for perhaps because of this he did depart for an hour, that age-duringly thou mayest have him,"
  },
  {
    "_id": "ylt-218001016",
    "version": "ylt",
    "chapter": "philemon-1",
    "sequence": "218001016",
    "number": 16,
    "text": "no more as a servant, but above a servant-a brother beloved, especially to me, and how much more to thee, both in the flesh and in the Lord!"
  },
  {
    "_id": "ylt-218001017",
    "version": "ylt",
    "chapter": "philemon-1",
    "sequence": "218001017",
    "number": 17,
    "text": "If, then, with me thou hast fellowship, receive him as me,"
  },
  {
    "_id": "ylt-218001018",
    "version": "ylt",
    "chapter": "philemon-1",
    "sequence": "218001018",
    "number": 18,
    "text": "and if he did hurt to thee, or doth owe anything, this to me be reckoning;"
  },
  {
    "_id": "ylt-218001019",
    "version": "ylt",
    "chapter": "philemon-1",
    "sequence": "218001019",
    "number": 19,
    "text": "I, Paul did write with my hand, I-I will repay; that I may not say that also thyself, besides, to me thou dost owe."
  },
  {
    "_id": "ylt-218001020",
    "version": "ylt",
    "chapter": "philemon-1",
    "sequence": "218001020",
    "number": 20,
    "text": "Yes, brother, may I have profit of thee in the Lord; refresh my bowels in the Lord;"
  },
  {
    "_id": "ylt-218001021",
    "version": "ylt",
    "chapter": "philemon-1",
    "sequence": "218001021",
    "number": 21,
    "text": "having been confident in thy obedience I did write to thee, having known that also above what I may say thou wilt do;"
  },
  {
    "_id": "ylt-218001022",
    "version": "ylt",
    "chapter": "philemon-1",
    "sequence": "218001022",
    "number": 22,
    "text": "and at the same time also prepare for me a lodging, for I hope that through your prayers I shall be granted to you."
  },
  {
    "_id": "ylt-218001023",
    "version": "ylt",
    "chapter": "philemon-1",
    "sequence": "218001023",
    "number": 23,
    "text": "Salute thee doth Epaphras, (my fellow-captive in Christ Jesus,)"
  },
  {
    "_id": "ylt-218001024",
    "version": "ylt",
    "chapter": "philemon-1",
    "sequence": "218001024",
    "number": 24,
    "text": "Markus, Aristarchus, Demas, Lukas, my fellow-workmen!"
  },
  {
    "_id": "ylt-218001025",
    "version": "ylt",
    "chapter": "philemon-1",
    "sequence": "218001025",
    "number": 25,
    "text": "The grace of our Lord Jesus Christ is with your spirit! Amen."
  }
]

=== LegendaryMediaTV/EGP-Graphai/exports/bb/WEBUS2020/57-PHM.json
[
  {
    "_id": "webp-218001001",
    "version": "webp",
    "chapter": "philemon-1",
    "sequence": "218001001",
    "number": 1,
    "text": "Paul, a prisoner of Christ° Jesus, and Timothy our brother, to Philemon, our beloved fellow worker,",
    "footnotes": [
      {
        "type": "stu",
        "text": "“Christ” means “Anointed One”."
      }
    ],
    "paragraphs": [0]
  },
  {
    "_id": "webp-218001002",
    "version": "webp",
    "chapter": "philemon-1",
    "sequence": "218001002",
    "number": 2,
    "text": "to the beloved Apphia, to Archippus our fellow soldier, and to the assembly in your house:"
  },
  {
    "_id": "webp-218001003",
    "version": "webp",
    "chapter": "philemon-1",
    "sequence": "218001003",
    "number": 3,
    "text": "Grace to you and peace from God our Father and the Lord Jesus Christ."
  },
  {
    "_id": "webp-218001004",
    "version": "webp",
    "chapter": "philemon-1",
    "sequence": "218001004",
    "number": 4,
    "text": "I thank my God always, making mention of you in my prayers,",
    "paragraphs": [0]
  },
  {
    "_id": "webp-218001005",
    "version": "webp",
    "chapter": "philemon-1",
    "sequence": "218001005",
    "number": 5,
    "text": "hearing of your love and of the faith which you have toward the Lord Jesus and toward all the saints,"
  },
  {
    "_id": "webp-218001006",
    "version": "webp",
    "chapter": "philemon-1",
    "sequence": "218001006",
    "number": 6,
    "text": "that the fellowship of your faith may become effective in the knowledge of every good thing which is in us in Christ Jesus."
  },
  {
    "_id": "webp-218001007",
    "version": "webp",
    "chapter": "philemon-1",
    "sequence": "218001007",
    "number": 7,
    "text": "For we have much joy and comfort in your love, because the hearts of the saints have been refreshed through you, brother."
  },
  {
    "_id": "webp-218001008",
    "version": "webp",
    "chapter": "philemon-1",
    "sequence": "218001008",
    "number": 8,
    "text": "Therefore though I have all boldness in Christ to command you that which is appropriate,",
    "paragraphs": [0]
  },
  {
    "_id": "webp-218001009",
    "version": "webp",
    "chapter": "philemon-1",
    "sequence": "218001009",
    "number": 9,
    "text": "yet for love’s sake I rather appeal to you, being such a one as Paul, the aged, but also a prisoner of Jesus Christ."
  },
  {
    "_id": "webp-218001010",
    "version": "webp",
    "chapter": "philemon-1",
    "sequence": "218001010",
    "number": 10,
    "text": "I appeal to you for my child Onesimus, whom I have become the father of in my chains,°",
    "footnotes": [
      {
        "type": "stu",
        "text": "Onesimus means “useful”."
      }
    ]
  },
  {
    "_id": "webp-218001011",
    "version": "webp",
    "chapter": "philemon-1",
    "sequence": "218001011",
    "number": 11,
    "text": "who once was useless to you, but now is useful to you and to me."
  },
  {
    "_id": "webp-218001012",
    "version": "webp",
    "chapter": "philemon-1",
    "sequence": "218001012",
    "number": 12,
    "text": "I am sending him back. Therefore receive him, that is, my own heart,"
  },
  {
    "_id": "webp-218001013",
    "version": "webp",
    "chapter": "philemon-1",
    "sequence": "218001013",
    "number": 13,
    "text": "whom I desired to keep with me, that on your behalf he might serve me in my chains for the Good News."
  },
  {
    "_id": "webp-218001014",
    "version": "webp",
    "chapter": "philemon-1",
    "sequence": "218001014",
    "number": 14,
    "text": "But I was willing to do nothing without your consent, that your goodness would not be as of necessity, but of free will."
  },
  {
    "_id": "webp-218001015",
    "version": "webp",
    "chapter": "philemon-1",
    "sequence": "218001015",
    "number": 15,
    "text": "For perhaps he was therefore separated from you for a while that you would have him forever,"
  },
  {
    "_id": "webp-218001016",
    "version": "webp",
    "chapter": "philemon-1",
    "sequence": "218001016",
    "number": 16,
    "text": "no longer as a slave, but more than a slave, a beloved brother—especially to me, but how much rather to you, both in the flesh and in the Lord."
  },
  {
    "_id": "webp-218001017",
    "version": "webp",
    "chapter": "philemon-1",
    "sequence": "218001017",
    "number": 17,
    "text": "If then you count me a partner, receive him as you would receive me.",
    "paragraphs": [0]
  },
  {
    "_id": "webp-218001018",
    "version": "webp",
    "chapter": "philemon-1",
    "sequence": "218001018",
    "number": 18,
    "text": "But if he has wronged you at all or owes you anything, put that to my account."
  },
  {
    "_id": "webp-218001019",
    "version": "webp",
    "chapter": "philemon-1",
    "sequence": "218001019",
    "number": 19,
    "text": "I, Paul, write this with my own hand: I will repay it (not to mention to you that you owe to me even your own self besides)."
  },
  {
    "_id": "webp-218001020",
    "version": "webp",
    "chapter": "philemon-1",
    "sequence": "218001020",
    "number": 20,
    "text": "Yes, brother, let me have joy from you in the Lord. Refresh my heart in the Lord."
  },
  {
    "_id": "webp-218001021",
    "version": "webp",
    "chapter": "philemon-1",
    "sequence": "218001021",
    "number": 21,
    "text": "Having confidence in your obedience, I write to you, knowing that you will do even beyond what I say.",
    "paragraphs": [0]
  },
  {
    "_id": "webp-218001022",
    "version": "webp",
    "chapter": "philemon-1",
    "sequence": "218001022",
    "number": 22,
    "text": "Also, prepare a guest room for me, for I hope that through your prayers I will be restored to you.",
    "paragraphs": [0]
  },
  {
    "_id": "webp-218001023",
    "version": "webp",
    "chapter": "philemon-1",
    "sequence": "218001023",
    "number": 23,
    "text": "Epaphras, my fellow prisoner in Christ Jesus, greets you,",
    "paragraphs": [0]
  },
  {
    "_id": "webp-218001024",
    "version": "webp",
    "chapter": "philemon-1",
    "sequence": "218001024",
    "number": 24,
    "text": "as do Mark, Aristarchus, Demas, and Luke, my fellow workers."
  },
  {
    "_id": "webp-218001025",
    "version": "webp",
    "chapter": "philemon-1",
    "sequence": "218001025",
    "number": 25,
    "text": "The grace of our Lord Jesus Christ be with your spirit. Amen.",
    "paragraphs": [0]
  }
]
