=== LegendaryMediaTV/EGP-Graphai/panta/bb-export-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "_id": {
        "type": "string",
        "pattern": "^[a-z0-9]+-[0-9]+$"
      },
      "version": {
        "type": "string",
        "minLength": 1
      },
      "chapter": {
        "type": "string",
        "pattern": "^[a-z0-9-]+-[0-9]+$"
      },
      "sequence": {
        "type": "string",
        "pattern": "^[0-9]+$"
      },
      "number": {
        "type": "number",
        "minimum": 1
      },
      "text": {
        "type": "string"
      },
      "paragraphs": {
        "type": "array",
        "items": {
          "type": "number",
          "minimum": 0
        }
      },
      "footnotes": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "text": {
              "type": "string"
            },
            "type": {
              "type": "string",
              "enum": ["trn", "var", "xrf", "map", "stu"]
            }
          },
          "required": ["text"],
          "additionalProperties": false
        }
      },
      "subtitle": {
        "type": "object",
        "properties": {
          "text": {
            "type": "string"
          },
          "footnotes": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "text": {
                  "type": "string"
                },
                "type": {
                  "type": "string",
                  "enum": ["trn", "var", "xrf", "map", "stu"]
                }
              },
              "required": ["text"],
              "additionalProperties": false
            }
          }
        },
        "required": ["text"],
        "additionalProperties": false
      }
    },
    "required": ["_id", "version", "chapter", "sequence", "number", "text"],
    "additionalProperties": false
  }
}

=== LegendaryMediaTV/EGP-Graphai/exports/bb/KJV1769/63-2JN.json
[
  {
    "_id": "kjv-224001001",
    "version": "kjv",
    "chapter": "2-john-1",
    "sequence": "224001001",
    "number": 1,
    "text": "The elder [strongs id=\"g4245\" /] unto the elect [strongs id=\"g1588\" /] lady [strongs id=\"g2959\" /] and [strongs id=\"g2532\" /] her [strongs id=\"g0846\" /] children [strongs id=\"g5043\" /], whom [strongs id=\"g3739\" /] I [strongs id=\"g1473\" /] love [strongs id=\"g0025\" m=\"PresActInd\" /] in [strongs id=\"g1722\" /] the truth [strongs id=\"g0225\" /]; and [strongs id=\"g2532\" /] not [strongs id=\"g3756\" /] I [strongs id=\"g1473\" /] only [strongs id=\"g3441\" /], but [strongs id=\"g0235\" /] also [strongs id=\"g2532\" /] all [strongs id=\"g3956\" /] they that have known [strongs id=\"g1097\" m=\"PerfActPtc\" /] the truth [strongs id=\"g0225\" /];",
    "paragraphs": [0]
  },
  {
    "_id": "kjv-224001002",
    "version": "kjv",
    "chapter": "2-john-1",
    "sequence": "224001002",
    "number": 2,
    "text": "For [strongs id=\"g1223\" /] the truthâ€™s sake [strongs id=\"g0225\" /], which [strongs id=\"g3588\" /] dwelleth [strongs id=\"g3306\" m=\"PresActPtc\" /] in [strongs id=\"g1722\" /] us [strongs id=\"g2254\" /], and [strongs id=\"g2532\" /] shall be [strongs id=\"g2071\" m=\"FutInd\" /] with [strongs id=\"g3326\" /] us [strongs id=\"g2257\" /] for [strongs id=\"g1519\" /] ever [strongs id=\"g0165\" /]."
  },
  {
    "_id": "kjv-224001003",
    "version": "kjv",
    "chapter": "2-john-1",
    "sequence": "224001003",
    "number": 3,
    "text": "Grace [strongs id=\"g5485\" /] be [strongs id=\"g2071\" m=\"FutInd\" /] with [strongs id=\"g3326\" /] you [strongs id=\"g5216\" /], mercy [strongs id=\"g1656\" /], [and] peace [strongs id=\"g1515\" /], from [strongs id=\"g3844\" /] God [strongs id=\"g2316\" /] the Father [strongs id=\"g3962\" /], and [strongs id=\"g2532\" /] from [strongs id=\"g3844\" /] the Lord [strongs id=\"g2962\" /] Jesus [strongs id=\"g2424\" /] Christ [strongs id=\"g5547\" /], the Son [strongs id=\"g5207\" /] of the Father [strongs id=\"g3962\" /], in [strongs id=\"g1722\" /] truth [strongs id=\"g0225\" /] and [strongs id=\"g2532\" /] love [strongs id=\"g0026\" /]."
  },
  {
    "_id": "kjv-224001004",
    "version": "kjv",
    "chapter": "2-john-1",
    "sequence": "224001004",
    "number": 4,
    "text": "I rejoiced [strongs id=\"g5463\" m=\"Aor2PasDepInd\" /] greatly [strongs id=\"g3029\" /] that [strongs id=\"g3754\" /] I found [strongs id=\"g2147\" m=\"PerfActInd\" /] of [strongs id=\"g1537\" /] thy [strongs id=\"g4675\" /] children [strongs id=\"g5043\" /] walking [strongs id=\"g4043\" m=\"PresActPtc\" /] in [strongs id=\"g1722\" /] truth [strongs id=\"g0225\" /], as [strongs id=\"g2531\" /] we have received [strongs id=\"g2983\" m=\"Aor2ActInd\" /] a commandment [strongs id=\"g1785\" /] from [strongs id=\"g3844\" /] the Father [strongs id=\"g3962\" /]."
  },
  {
    "_id": "kjv-224001005",
    "version": "kjv",
    "chapter": "2-john-1",
    "sequence": "224001005",
    "number": 5,
    "text": "And [strongs id=\"g2532\" /] now [strongs id=\"g3568\" /] I beseech [strongs id=\"g2065\" m=\"PresActInd\" /] thee [strongs id=\"g4571\" /], lady [strongs id=\"g2959\" /], not [strongs id=\"g3756\" /] as though [strongs id=\"g5613\" /] I wrote [strongs id=\"g1125\" m=\"PresActInd\" /] [strongs id=\"g1125\" m=\"PresActPtc\" /] a new [strongs id=\"g2537\" /] commandment [strongs id=\"g1785\" /] unto thee [strongs id=\"g4671\" /], but [strongs id=\"g0235\" /] that which [strongs id=\"g3739\" /] we had [strongs id=\"g2192\" m=\"ImpfActInd\" /] from [strongs id=\"g0575\" /] the beginning [strongs id=\"g0746\" /], that [strongs id=\"g2443\" /] we love [strongs id=\"g0025\" m=\"PresActSubj\" /] one another [strongs id=\"g0240\" /]."
  },
  {
    "_id": "kjv-224001006",
    "version": "kjv",
    "chapter": "2-john-1",
    "sequence": "224001006",
    "number": 6,
    "text": "And [strongs id=\"g2532\" /] this [strongs id=\"g3778\" /] is [strongs id=\"g2076\" m=\"PresInd\" /] love [strongs id=\"g0026\" /], that [strongs id=\"g2443\" /] we walk [strongs id=\"g4043\" m=\"PresActSubj\" /] after [strongs id=\"g2596\" /] his [strongs id=\"g0846\" /] commandments [strongs id=\"g1785\" /]. This [strongs id=\"g3778\" /] is [strongs id=\"g2076\" m=\"PresInd\" /] the commandment [strongs id=\"g1785\" /], That [strongs id=\"g2443\" /], as [strongs id=\"g2531\" /] ye have heard [strongs id=\"g0191\" m=\"AorActInd\" /] from [strongs id=\"g0575\" /] the beginning [strongs id=\"g0746\" /], ye should walk [strongs id=\"g4043\" m=\"PresActSubj\" /] in [strongs id=\"g1722\" /] it [strongs id=\"g0846\" /]."
  },
  {
    "_id": "kjv-224001007",
    "version": "kjv",
    "chapter": "2-john-1",
    "sequence": "224001007",
    "number": 7,
    "text": "For [strongs id=\"g3754\" /] many [strongs id=\"g4183\" /] deceivers [strongs id=\"g4108\" /] are entered [strongs id=\"g1525\" m=\"Aor2ActInd\" /] into [strongs id=\"g1519\" /] the world [strongs id=\"g2889\" /], who [strongs id=\"g3588\" /] confess [strongs id=\"g3670\" m=\"PresActPtc\" /] not [strongs id=\"g3361\" /] that Jesus [strongs id=\"g2424\" /] Christ [strongs id=\"g5547\" /] is come [strongs id=\"g2064\" m=\"PresMidPasDepPtc\" /] in [strongs id=\"g1722\" /] the flesh [strongs id=\"g4561\" /]. This [strongs id=\"g3778\" /] is [strongs id=\"g2076\" m=\"PresInd\" /] a deceiver [strongs id=\"g4108\" /] and [strongs id=\"g2532\" /] an antichrist [strongs id=\"g0500\" /]."
  },
  {
    "_id": "kjv-224001008",
    "version": "kjv",
    "chapter": "2-john-1",
    "sequence": "224001008",
    "number": 8,
    "text": "Look [strongs id=\"g0991\" m=\"PresActImpr\" /] to yourselves [strongs id=\"g1438\" /], that we lose [strongs id=\"g0622\" m=\"AorActSubj\" /] not [strongs id=\"g3363\" /] those things which [strongs id=\"g3739\" /] we have wrought [strongs id=\"g2038\" m=\"AorMidDepInd\" /], but [strongs id=\"g0235\" /] that we receive [strongs id=\"g0618\" m=\"Aor2ActSubj\" /] a full [strongs id=\"g4134\" /] reward [strongs id=\"g3408\" /]."
  },
  {
    "_id": "kjv-224001009",
    "version": "kjv",
    "chapter": "2-john-1",
    "sequence": "224001009",
    "number": 9,
    "text": "Whosoever [strongs id=\"g3956\" /] transgresseth [strongs id=\"g3845\" m=\"PresActPtc\" /], and [strongs id=\"g2532\" /] abideth [strongs id=\"g3306\" m=\"PresActPtc\" /] not [strongs id=\"g3361\" /] in [strongs id=\"g1722\" /] the doctrine [strongs id=\"g1322\" /] of Christ [strongs id=\"g5547\" /], hath [strongs id=\"g2192\" m=\"PresActInd\" /] not [strongs id=\"g3756\" /] God [strongs id=\"g2316\" /]. He that abideth [strongs id=\"g3306\" m=\"PresActPtc\" /] in [strongs id=\"g1722\" /] the doctrine [strongs id=\"g1322\" /] of Christ [strongs id=\"g5547\" /], he [strongs id=\"g3778\" /] hath [strongs id=\"g2192\" m=\"PresActInd\" /] both [strongs id=\"g2532\" /] the Father [strongs id=\"g3962\" /] and [strongs id=\"g2532\" /] the Son [strongs id=\"g5207\" /]."
  },
  {
    "_id": "kjv-224001010",
    "version": "kjv",
    "chapter": "2-john-1",
    "sequence": "224001010",
    "number": 10,
    "text": "If [strongs id=\"g1536\" /] there come [strongs id=\"g2064\" m=\"PresMidPasDepInd\" /] any [strongs id=\"g1536\" /] [strongs id=\"g5100\" /] unto [strongs id=\"g4314\" /] you [strongs id=\"g5209\" /], and [strongs id=\"g2532\" /] bring [strongs id=\"g5342\" m=\"PresActInd\" /] not [strongs id=\"g3756\" /] this [strongs id=\"g5026\" /] doctrine [strongs id=\"g1322\" /], receive [strongs id=\"g2983\" m=\"PresActImpr\" /] him [strongs id=\"g0846\" /] not [strongs id=\"g3361\" /] into [strongs id=\"g1519\" /] [your] house [strongs id=\"g3614\" /], neither [strongs id=\"g2532\" /] [strongs id=\"g3361\" /] bid [strongs id=\"g3004\" m=\"PresActImpr\" /] him [strongs id=\"g0846\" /] God speed [strongs id=\"g5463\" m=\"PresActInf\" /]:"
  },
  {
    "_id": "kjv-224001011",
    "version": "kjv",
    "chapter": "2-john-1",
    "sequence": "224001011",
    "number": 11,
    "text": "For [strongs id=\"g1063\" /] he that biddeth [strongs id=\"g3004\" m=\"PresActPtc\" /] him [strongs id=\"g0846\" /] God speed [strongs id=\"g5463\" m=\"PresActInf\" /] is partaker [strongs id=\"g2841\" m=\"PresActInd\" /] of his [strongs id=\"g0846\" /] evil [strongs id=\"g4190\" /] deeds [strongs id=\"g2041\" /]."
  },
  {
    "_id": "kjv-224001012",
    "version": "kjv",
    "chapter": "2-john-1",
    "sequence": "224001012",
    "number": 12,
    "text": "Having [strongs id=\"g2192\" m=\"PresActPtc\" /] many things [strongs id=\"g4183\" /] to write [strongs id=\"g1125\" m=\"PresActInf\" /] unto you [strongs id=\"g5213\" /], I would [strongs id=\"g1014\" m=\"AorPasDepInd\" /] not [strongs id=\"g3756\" /] [write] with [strongs id=\"g1223\" /] paper [strongs id=\"g5489\" /] and [strongs id=\"g2532\" /] ink [strongs id=\"g3188\" /]: but [strongs id=\"g0235\" /] I trust [strongs id=\"g1679\" m=\"PresActInd\" /] to come [strongs id=\"g2064\" m=\"Aor2ActInf\" /] unto [strongs id=\"g4314\" /] you [strongs id=\"g5209\" /], and [strongs id=\"g2532\" /] speak [strongs id=\"g2980\" m=\"AorActInf\" /] face [strongs id=\"g4750\" /] to [strongs id=\"g4314\" /] face [strongs id=\"g4750\" /], that [strongs id=\"g2443\" /] our [strongs id=\"g2257\" /] joy [strongs id=\"g5479\" /] may be [strongs id=\"g5600\" m=\"PresSubj\" /] full [strongs id=\"g4137\" m=\"PerfPasPtc\" /]."
  },
  {
    "_id": "kjv-224001013",
    "version": "kjv",
    "chapter": "2-john-1",
    "sequence": "224001013",
    "number": 13,
    "text": "The children [strongs id=\"g5043\" /] of thy [strongs id=\"g4675\" /] elect [strongs id=\"g1588\" /] sister [strongs id=\"g0079\" /] greet [strongs id=\"g0782\" m=\"PresMidPasDepInd\" /] thee [strongs id=\"g4571\" /]. Amen [strongs id=\"g0281\" /]."
  }
]

=== LegendaryMediaTV/EGP-Graphai/exports/bb/CLV1880/57-PHM.json
[
  {
    "_id": "vul-218001001",
    "version": "vul",
    "chapter": "philemon-1",
    "sequence": "218001001",
    "number": 1,
    "text": "Paulus vinctus Iesu Christi et Timotheus frater Philemoni dilecto et adiutori nostro",
    "paragraphs": [0]
  },
  {
    "_id": "vul-218001002",
    "version": "vul",
    "chapter": "philemon-1",
    "sequence": "218001002",
    "number": 2,
    "text": "et Appiae sorori et Archippo commilitoni nostro et ecclesiae quae in domo tua est"
  },
  {
    "_id": "vul-218001003",
    "version": "vul",
    "chapter": "philemon-1",
    "sequence": "218001003",
    "number": 3,
    "text": "gratia vobis et pax a Deo Patre nostro et Domino Iesu Christo"
  },
  {
    "_id": "vul-218001004",
    "version": "vul",
    "chapter": "philemon-1",
    "sequence": "218001004",
    "number": 4,
    "text": "gratias ago Deo meo semper memoriam tui faciens in orationibus meis"
  },
  {
    "_id": "vul-218001005",
    "version": "vul",
    "chapter": "philemon-1",
    "sequence": "218001005",
    "number": 5,
    "text": "audiens caritatem tuam et fidem quam habes in Domino Iesu et in omnes sanctos"
  },
  {
    "_id": "vul-218001006",
    "version": "vul",
    "chapter": "philemon-1",
    "sequence": "218001006",
    "number": 6,
    "text": "ut communicatio fidei tuae evidens fiat in agnitione omnis boni in nobis in Christo Iesu"
  },
  {
    "_id": "vul-218001007",
    "version": "vul",
    "chapter": "philemon-1",
    "sequence": "218001007",
    "number": 7,
    "text": "gaudium enim magnum habui et consolationem in caritate tua quia viscera sanctorum requieverunt per te frater"
  },
  {
    "_id": "vul-218001008",
    "version": "vul",
    "chapter": "philemon-1",
    "sequence": "218001008",
    "number": 8,
    "text": "propter quod multam fiduciam habentes in Christo Iesu imperandi tibi quod ad rem pertinet"
  },
  {
    "_id": "vul-218001009",
    "version": "vul",
    "chapter": "philemon-1",
    "sequence": "218001009",
    "number": 9,
    "text": "propter caritatem magis obsecro cum sis talis ut Paulus senex nunc autem et vinctus Iesu Christi"
  },
  {
    "_id": "vul-218001010",
    "version": "vul",
    "chapter": "philemon-1",
    "sequence": "218001010",
    "number": 10,
    "text": "obsecro te de meo filio quem genui in vinculis Onesimo"
  },
  {
    "_id": "vul-218001011",
    "version": "vul",
    "chapter": "philemon-1",
    "sequence": "218001011",
    "number": 11,
    "text": "qui tibi aliquando inutilis fuit nunc autem et tibi et mihi utilis"
  },
  {
    "_id": "vul-218001012",
    "version": "vul",
    "chapter": "philemon-1",
    "sequence": "218001012",
    "number": 12,
    "text": "quem remisi tu autem illum id est mea viscera suscipe"
  },
  {
    "_id": "vul-218001013",
    "version": "vul",
    "chapter": "philemon-1",
    "sequence": "218001013",
    "number": 13,
    "text": "quem ego volueram mecum detinere ut pro te mihi ministraret in vinculis evangelii"
  },
  {
    "_id": "vul-218001014",
    "version": "vul",
    "chapter": "philemon-1",
    "sequence": "218001014",
    "number": 14,
    "text": "sine consilio autem tuo nihil volui facere uti ne velut ex necessitate bonum tuum esset sed voluntarium"
  },
  {
    "_id": "vul-218001015",
    "version": "vul",
    "chapter": "philemon-1",
    "sequence": "218001015",
    "number": 15,
    "text": "forsitan enim ideo discessit ad horam a te ut aeternum illum recipere"
  },
  {
    "_id": "vul-218001016",
    "version": "vul",
    "chapter": "philemon-1",
    "sequence": "218001016",
    "number": 16,
    "text": "iam non ut servum sed plus servo carissimum fratrem maxime mihi quanto autem magis tibi et in carne et in Domino"
  },
  {
    "_id": "vul-218001017",
    "version": "vul",
    "chapter": "philemon-1",
    "sequence": "218001017",
    "number": 17,
    "text": "si ergo habes me socium suscipe illum sicut me"
  },
  {
    "_id": "vul-218001018",
    "version": "vul",
    "chapter": "philemon-1",
    "sequence": "218001018",
    "number": 18,
    "text": "si autem aliquid nocuit tibi aut debet hoc mihi inputa"
  },
  {
    "_id": "vul-218001019",
    "version": "vul",
    "chapter": "philemon-1",
    "sequence": "218001019",
    "number": 19,
    "text": "ego Paulus scripsi mea manu ego reddam ut non dicam tibi quod et te ipsum mihi debes"
  },
  {
    "_id": "vul-218001020",
    "version": "vul",
    "chapter": "philemon-1",
    "sequence": "218001020",
    "number": 20,
    "text": "ita frater ego te fruar in Domino refice viscera mea in Domino"
  },
  {
    "_id": "vul-218001021",
    "version": "vul",
    "chapter": "philemon-1",
    "sequence": "218001021",
    "number": 21,
    "text": "confidens oboedientia tua scripsi tibi sciens quoniam et super id quod dico facies"
  },
  {
    "_id": "vul-218001022",
    "version": "vul",
    "chapter": "philemon-1",
    "sequence": "218001022",
    "number": 22,
    "text": "simul autem et para mihi hospitium nam spero per orationes vestras donari me vobis"
  },
  {
    "_id": "vul-218001023",
    "version": "vul",
    "chapter": "philemon-1",
    "sequence": "218001023",
    "number": 23,
    "text": "salutat te Epaphras concaptivus meus in Christo Iesu"
  },
  {
    "_id": "vul-218001024",
    "version": "vul",
    "chapter": "philemon-1",
    "sequence": "218001024",
    "number": 24,
    "text": "Marcus Aristarchus Demas Lucas adiutores mei"
  },
  {
    "_id": "vul-218001025",
    "version": "vul",
    "chapter": "philemon-1",
    "sequence": "218001025",
    "number": 25,
    "text": "gratia Domini nostri Iesu Christi cum spiritu vestro amen"
  }
]

=== LegendaryMediaTV/EGP-Graphai/exports/bb/YLT1898/65-JUD.json
[
  {
    "_id": "ylt-226001001",
    "version": "ylt",
    "chapter": "jude-1",
    "sequence": "226001001",
    "number": 1,
    "text": "Judas, of Jesus Christ a servant, and brother of James, to those sanctified in God the Father, and in Jesus Christ kept-called,",
    "paragraphs": [0]
  },
  {
    "_id": "ylt-226001002",
    "version": "ylt",
    "chapter": "jude-1",
    "sequence": "226001002",
    "number": 2,
    "text": "kindness to you, and peace, and love, be multiplied!"
  },
  {
    "_id": "ylt-226001003",
    "version": "ylt",
    "chapter": "jude-1",
    "sequence": "226001003",
    "number": 3,
    "text": "Beloved, all diligence using to write to you concerning the common salvation, I had necessity to write to you, exhorting to agonize for the faith once delivered to the saints,"
  },
  {
    "_id": "ylt-226001004",
    "version": "ylt",
    "chapter": "jude-1",
    "sequence": "226001004",
    "number": 4,
    "text": "for there did come in unobserved certain men, long ago having been written beforehand to this judgment, impious, the grace of our God perverting to lasciviousness, and our only Master, God, and Lord-Jesus Christ-denying,"
  },
  {
    "_id": "ylt-226001005",
    "version": "ylt",
    "chapter": "jude-1",
    "sequence": "226001005",
    "number": 5,
    "text": "and to remind you I intend, you knowing once this, that the Lord, a people out of the land of Egypt having saved, again those who did not believe did destroy;"
  },
  {
    "_id": "ylt-226001006",
    "version": "ylt",
    "chapter": "jude-1",
    "sequence": "226001006",
    "number": 6,
    "text": "messengers also, those who did not keep their own principality, but did leave their proper dwelling, to a judgment of a great day, in bonds everlasting, under darkness He hath kept,"
  },
  {
    "_id": "ylt-226001007",
    "version": "ylt",
    "chapter": "jude-1",
    "sequence": "226001007",
    "number": 7,
    "text": "as Sodom and Gomorrah, and the cities around them, in like manner to these, having given themselves to whoredom, and gone after other flesh, have been set before-an example, of fire age-during, justice suffering."
  },
  {
    "_id": "ylt-226001008",
    "version": "ylt",
    "chapter": "jude-1",
    "sequence": "226001008",
    "number": 8,
    "text": "In like manner, nevertheless, those dreaming also the flesh indeed do defile, and lordship they put away, and dignities they speak evil of,"
  },
  {
    "_id": "ylt-226001009",
    "version": "ylt",
    "chapter": "jude-1",
    "sequence": "226001009",
    "number": 9,
    "text": "yet Michael, the chief messenger, when, with the devil contending, he was disputing about the body of Moses, did not dare to bring up an evil-speaking judgment, but said, ‘The Lord rebuke thee!’"
  },
  {
    "_id": "ylt-226001010",
    "version": "ylt",
    "chapter": "jude-1",
    "sequence": "226001010",
    "number": 10,
    "text": "and these, as many things indeed as they have not known, they speak evil of; and as many things as naturally (as the irrational beasts) they understand, in these they are corrupted;"
  },
  {
    "_id": "ylt-226001011",
    "version": "ylt",
    "chapter": "jude-1",
    "sequence": "226001011",
    "number": 11,
    "text": "woe to them! because in the way of Cain they did go on, and to the deceit of Balaam for reward they did rush, and in the gainsaying of Korah they did perish."
  },
  {
    "_id": "ylt-226001012",
    "version": "ylt",
    "chapter": "jude-1",
    "sequence": "226001012",
    "number": 12,
    "text": "These are in your love-feasts craggy rocks; feasting together with you, without fear shepherding themselves; clouds without water, by winds carried about; trees autumnal, without fruit, twice dead, rooted up;"
  },
  {
    "_id": "ylt-226001013",
    "version": "ylt",
    "chapter": "jude-1",
    "sequence": "226001013",
    "number": 13,
    "text": "wild waves of a sea, foaming out their own shames; stars going astray, to whom the gloom of the darkness to the age hath been kept."
  },
  {
    "_id": "ylt-226001014",
    "version": "ylt",
    "chapter": "jude-1",
    "sequence": "226001014",
    "number": 14,
    "text": "And prophesy also to these did the seventh from Adam-Enoch-saying, ‘Lo, the Lord did come in His saintly myriads,"
  },
  {
    "_id": "ylt-226001015",
    "version": "ylt",
    "chapter": "jude-1",
    "sequence": "226001015",
    "number": 15,
    "text": "to do judgment against all, and to convict all their impious ones, concerning all their works of impiety that they did impiously, and concerning all the stiff things that speak against Him did impious sinners.’"
  },
  {
    "_id": "ylt-226001016",
    "version": "ylt",
    "chapter": "jude-1",
    "sequence": "226001016",
    "number": 16,
    "text": "These are murmurers, repiners; according to their desires walking, and their mouth doth speak great swellings, giving admiration to persons for the sake of profit;"
  },
  {
    "_id": "ylt-226001017",
    "version": "ylt",
    "chapter": "jude-1",
    "sequence": "226001017",
    "number": 17,
    "text": "and ye, beloved, remember ye the sayings spoken before by the apostles of our Lord Jesus Christ:"
  },
  {
    "_id": "ylt-226001018",
    "version": "ylt",
    "chapter": "jude-1",
    "sequence": "226001018",
    "number": 18,
    "text": "that they said to you, that in the last time there shall be scoffers, after their own desires of impieties going on,"
  },
  {
    "_id": "ylt-226001019",
    "version": "ylt",
    "chapter": "jude-1",
    "sequence": "226001019",
    "number": 19,
    "text": "these are those setting themselves apart, natural men, the Spirit not having."
  },
  {
    "_id": "ylt-226001020",
    "version": "ylt",
    "chapter": "jude-1",
    "sequence": "226001020",
    "number": 20,
    "text": "And ye, beloved, on your most holy faith building yourselves up, in the Holy Spirit praying,"
  },
  {
    "_id": "ylt-226001021",
    "version": "ylt",
    "chapter": "jude-1",
    "sequence": "226001021",
    "number": 21,
    "text": "yourselves in the love of God keep ye, waiting for the kindness of our Lord Jesus Christ-to life age-during;"
  },
  {
    "_id": "ylt-226001022",
    "version": "ylt",
    "chapter": "jude-1",
    "sequence": "226001022",
    "number": 22,
    "text": "and to some be kind, judging thoroughly,"
  },
  {
    "_id": "ylt-226001023",
    "version": "ylt",
    "chapter": "jude-1",
    "sequence": "226001023",
    "number": 23,
    "text": "and some in fear save ye, out of the fire snatching, hating even the coat from the flesh spotted."
  },
  {
    "_id": "ylt-226001024",
    "version": "ylt",
    "chapter": "jude-1",
    "sequence": "226001024",
    "number": 24,
    "text": "And to Him who is able to guard you not stumbling, and to set you in the presence of His glory unblemished, in gladness,"
  },
  {
    "_id": "ylt-226001025",
    "version": "ylt",
    "chapter": "jude-1",
    "sequence": "226001025",
    "number": 25,
    "text": "to the only wise God our Saviour, is glory and greatness, power and authority, both now and to all the ages! Amen."
  }
]
